### PR TITLE
Support quoted params in Contact header

### PR DESCRIPTION
**Pull request by vasilakisfil**
+ add explicit contact header struct and parser
+ introduce GenValue that holds both regular and quoted strigns
+ add some useful traits on the GenValue

### CODE REVIEW

**Comment by bytebuddha** [comment]
This works for me thank you for your effort, If you could fix the merge conflict i will merge in core/message_ext.rs i will merge this

**Comment by vasilakisfil** [comment]
fixed!

**Comment by bytebuddha** [comment]
Thanks Again!

**Comment by KalitaAlexey** [comment]
I've just seen this PR. Is there a reason only the Contact header now supports correct writing of quoted strings?

**Comment by vasilakisfil** [comment]
@KalitaAlexey I thought it was very rare to have quoted strings in From/To headers.. but I am not against having it there as well. Generally quoted strings are found through RFC 3840 that extends the Contact header, but again I am not an expert.

**Pull request merged**
