### PR TITLE
Use Result in headers to make it easier for users of library to use ?

### PR DESCRIPTION
**Pull request by KalitaAlexey**
Basically I had to have a lot of if let Some(header) = ...
This commit enables me to have some Error and use ? to convert all these errors into it.

### CODE REVIEW

**Comment by bytebuddha** [comment]
Is there any reason to not use an enum for this? Something like
```rust
pub enum MissingHeaderError {
   Contact,
   To,
   ...
}
```

This would make importing in your project easier and simplify writing the error logic

**Comment by KalitaAlexey** [comment]
I don't know. I thought about it, declined it and now I think it's better.

**Comment by bytebuddha** [comment]
Now that i think about it Having that many separate errors would make implementing traits on them a daunting task It's probably better to keep them confined to one object. An enum would be the simplest to implement but a struct could similarly be used

**Comment by bytebuddha** [comment]
@KalitaAlexey I forgot another solution would be to implement std::option::NoneError for your error in your code, then you could use ? on the option directly. I forget rust added ? support to option relatively recently

Using option feels most right to me, since a missing header isn't necessarily an error but I'd prefer witch ever one makes it easier for the library to be used.

**Comment by KalitaAlexey** [comment]
@bytebuddha I know about it. I specifically want a separate error for each case because it makes easier for logging purposes.

**Comment by bytebuddha** [comment]
Ah yeah good point. I'm not sure how you would get the the requested error from NoneError. Then the last thing i can think of is could you derive Debug, Clone & PartialEq for the error types? I tend to use those a lot when debugging and testing

**Pull request merged**
