### PR TITLE
Introduce SipMessageError

### LINKED ISSUE #19: Provide SipMessageError instead of many Missing...
I was thinking about adding more errors to such functions as method, status_code and etc.
I realized that it would make developers' life miserable because there will be more errors to handle.
I'm going to provide a pull request to provide only 1 error - `enum SipMessageError`

### PR DESCRIPTION
**Pull request by KalitaAlexey**
Fixes #19

### CODE REVIEW

**Comment by KalitaAlexey** [comment]
Don't merge.

**Comment by vasilakisfil** [comment]
There are still some errors. That PR would indeed be helpful for me as well.

**Comment by KalitaAlexey** [comment]
Interesting. I could not push something that I didn't even had built.

**Comment by bytebuddha** [comment]
Looks good to me, Thanks :)

**Pull request merged**
